[advisories]
version = 2

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "ISC",
    "MIT",
]
confidence-threshold = 1.0

[bans]
# We don't maintain a fixed Cargo.lock so enforcing
# `multiple-versions = "deny"` is impractical.
multiple-versions = "allow"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
